update columns creation (type defintion) and columns update if type c…
dacker-team/pyred pull request #10
Opened 2020-09-08 09:04 UTC by elie-sgn

- type definition for creation of columns
- type modification if new type in column

2020-09-08 12:13 UTC, pflucet requested changes

2020-09-08 12:13 UTC, pflucet commented on pyred/core/Column.py
> +            type_to_float(_dbstream, table_name=data["table_name"], column_name=c)
Rajouter un test sur le type actuel de la colonne , à charger auparavant avec get_columns_length (qu'on pourrait renommer...)

2020-09-08 12:13 UTC, pflucet commented on pyred/core/Column.py
>          df[name] = df[name].apply(lambda x: (str(x.encode()) if isinstance(x, str) else x) if x is not None else '')
Attention au Big int --> il faut prendre le plus grand

2020-09-08 12:13 UTC, pflucet commented on pyred/core/Column.py
>          df[name] = df[name].apply(lambda x: (str(x.encode()) if isinstance(x, str) else x) if x is not None else '')
Vérifier si le test sur le type "object" est nécessaire

2020-09-09 09:44 UTC, elie-sgn commented on pyred/core/Column.py
> +            type_to_float(_dbstream, table_name=data["table_name"], column_name=c)
nouvelle fonction get_columns_type pour ne pas être dérangé avec les character_maximal_length = None dans le cas d'un int, d'un foat ou d'un bool

2020-09-09 10:06 UTC, elie-sgn commented on pyred/RedDBStream.py
> +            if "invalid input syntax for integer" in str(e).lower():
cas pris en compte:
- int -> str // int -> float // int -> big int
- big int -> str // big int -> float
- float -> str

2020-09-18 13:14 UTC, merged